sonar.projectKey=aeds
sonar.projectName=aeds
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000

sonar.inclusions=**/*.c,**/*.h
sonar.exclusions=build/**,.scannerwork/**

sonar.cfamily.compile-commands=bw-output/compile_commands.json
